origami/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Category, Product, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db


bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    categories = Category.query.order_by(Category.name).all()
    return render_template('index.html', categories = categories)

#add search function
@bp.route('/product/')
def search():
	search = request.args.get('search')
	search = '%{}%'.format(search)
	products = Product.query.filter(Product.description.like(search)).all()
	return render_template('products.html', products = products)

@bp.route('/product/<int:categoryid>/')
def categoryproducts(categoryid):
    products = Product.query.filter(Product.category_id == categoryid)
    return render_template('products.html', products = products)


# Cart settings
@bp.route('/order', methods=['POST','GET'])
def order():
    product_id = request.values.get('product_id')

    # retrieve order if there is one
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', address='', postcode='', request='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for product in order.products:
            totalprice = totalprice + product.price
    
    # are we adding an item?
    if product_id is not None and order is not None:
        product = Product.query.get(product_id)
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your cart'
            return redirect(url_for('main.order'))
        else:
            flash('The item is already in your cart')
            return redirect(url_for('main.order'))
    
    return render_template('order.html', order = order, totalprice = totalprice)


# Delete specific cart items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        product_to_delete = Product.query.get(id)
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))


# Empty cart
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items in your shopping cart have been deleted.')
    return redirect(url_for('main.order'))


@bp.route('/checkout', methods=['POST','GET']) 
def checkout():

    # retrieve order if there is one for checkout
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # calcultate totalprice for checkout
    totalprice = 0
    if order is not None:
        for product in order.products:
            totalprice = totalprice + product.price

    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.postcode = form.postcode.data
            order.address = form.address.data
            order.request = form.request.data
            totalcost = 0
            for product in order.products:
                totalcost = totalcost + product.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('All done! Your purchased products will deliver to your address soon...')
                return redirect(url_for('main.checkout'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', order = order, totalprice = totalprice, form = form)

origami/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

<meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="description" content="NIPPON ORIGAMI delivers various origami products to all over the world">
    <!-- Bootstrap Required Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>NIPPON ORIGAMI</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Custom CSS -->
<style type="text/css">
html {scroll-behavior: smooth;}
h2,h3{color:#57734A;margin-top:25px;padding-bottom:10px;}
h2,.navbar-brand{font-weight:777;}
h4{color:#756F55;}
nav{background: #EBE9DA;}
.alert{font-weight:bold;}
.navbar img{margin-top:-5px;}
.jumbotron{background:center / cover no-repeat url({{url_for('static', filename='img/header2.jpg')}});color:#EBE9DA;}
.btn{background:#398793;border:none;}
.btn-default{background:#ff7a00b8;color:#fff;margin-bottom:30px;}
.btn-default:hover{background:#ff4b00;margin-bottom:30px;color:#fff;}
.empty{background:none;border:1px solid #ddd;}
.outer{min-width:300px;}
.mycontents{max-width:980px;margin:auto;}
#myTab{margin-top:30px;}
.card-deck{margin-bottom:20px;}
.upper{margin-bottom:5px;}
.carousel{margin-bottom:50px;}
.carousel-caption{background:rgba(45, 52, 60,0.9); position:absolute; bottom:0; left:0; width:100%;}
footer{background:#EBE9DA;border-top:10px solid  #57734A;}
</style>
</head>

<body>
<div class="outer">
<!-- Bootstrap Navbar -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{url_for('static', filename='img/logo.png')}}" width="30" class="upper"
                    alt="NIPPON ORIGAMI Logo">
                NIPPON ORIGAMI
            </a>

              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.index', _anchor='categories_anchor')}}">Products</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.order')}}"><img src="{{url_for('static', filename='img/cart.png')}}" width="20"> View Cart</a></li>
              <li class="nav-item"><a class="nav-link" href="nopage.html">NoPage</a></li>
              </ul>
                        <!-- search box -->
                        <form class="form-inline my-2 my-lg-0" action="{{url_for('main.search')}}">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search">
                            <button class="btn btn-primary btn-s my-0 ml-1" type="submit">Search</button>
                        </form>
            </div>
        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        {% block head %}{% endblock %}

    </header>


    <!-- main page content goes in container -->
    
    <div class="container-fluid">
        <main>
            {% block main %}{% endblock %}
        </main>
    </div>

<!-- Footer -->
</div>
<footer class="text-center text-lg-start text-muted" id="contact">
<section class="d-flex justify-content-center justify-content-lg-between p-2">
    <div class="container text-center text-md-start mt-2">

        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-md-0 mb-2">
          <h4 class="text-uppercase">Contact</h4>
          <p>Tokyo, Japan<br>
            info@example.com<br>
         + 81 234 567 89</p>
        </div>
<!-- GoogleMaps -->
<iframe src="https://www.google.com/maps/embed?pb=%211m18%211m12%211m3%211d1769.866932540282%212d153.02702597603235%213d-27.477543616066125%212m3%211f0%212f0%213f0%213m2%211i1024%212i768%214f13.1%213m3%211m2%211s0x0%3A0x0%212zMjfCsDI4JzM5LjIiUyAxNTPCsDAxJzQxLjIiRQ%215e0%213m2%211sen%212sjp%214v1621576419553%215m2%211sen%212sjp" style="border:0;" allowfullscreen="" loading="lazy" height="250" width="100%"></iframe>

      </div>

</section>

  <div class="text-center p-4">
    All rights belong to their respective owners.
  </div>

</footer>
    <!-- Footer -->


<!-- jQuery first, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

origami/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}
<div class="mycontents">
    <section>  
        <div class="container">
            <div class="row">
                <div class = "col-12">
                    <h2 class="text-center">Place Your Order Now!</h2>
                    <p>
                        Thank you for your order. Please confirm your order and enter shipping details so that we can complete your order. Arigato! 
                    </p>
                </div>
            </div>
            <div class="card">
            <div class="card-header"><h5>You are ordering (Total Price {{ "$%.2f"|format(totalprice) }})</h5></div>
  <div class="card-body">
            <!-- display ordering products to confirm -->
            <ol style="font-weight:bold;">
        {% for product in order.products %}
                <li><img class="img-thumbnail" src="{{url_for('static', filename=('img/' + product.image))}}" width="100">
                {{product.name}}: {{ "$%.2f"|format(product.price) }}
                </li>
        {% endfor %}
        </ol>
        </div>
        </div>
        <!-- submission form -->
        <p><br>* Required fields</p>
            <div class="row">
                <div class = "col-6">
                    {{wtf.quick_form(form)}}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

origami/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Folding Origami<br> Expands Your Possibilities</h1>
    <p class="lead">Get creative with playing ORIGAMI.</p>
  </div>
</div>
{% endblock %}

{% block main %}
<div class="mycontents">
<!-- our information -->
<p>!!! SOME IMAGES ARE REMOVED FOR COPYRIGHT PROTECTION !!!</p>
<section>
<h2 id="products">What's NIPPON ORIGAMI?</h2>
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{url_for('static', filename='img/kangaroo.jpg')}}" width="300" alt="kangaroo">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Japanese traditional play has transformed into the latest technology</h5>
        <p class="card-text">I sell various origami products to introduce the charms of Japanese traditional origami to all over the world. The store will also provide an excellent opportunity for adults and children during the time they spend at home due to COVID-19, not only killing time but also to be creative by making origami. To satisfy both beginners and advanced users, the store will provide from already completed origami to the latest computer designed complex origami products/software.</p>
        <p class="card-text"><small class="text-muted">This website was created for a web development assignment.</small></p>
</div>
</div>
</div></div>
</section>

<!-- categories -->
<section>
    <h2 id="categories_anchor">Select Product Categories</h2>

    <div class="card-deck">

        {% for category in categories%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+category.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{category.name}}</h4>
                <p class="card-text">{{category.description}}</p>
            </div>
            <div class="card-footer"><a href= "{{ url_for('main.categoryproducts', categoryid=category.id) }}" class="btn btn-primary">Choose Products</a></div>
        </div>
        {% endfor %}
    </div>
</section>

<!-- Bootstrap Carousel -->
<h2>Origami Showcase</h2>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"><br></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"><br></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"><br></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{url_for('static', filename='img/header1.jpg')}}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Origami Paint Art</h5>
        <p>Cute origami paint by an talented artist</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{{url_for('static', filename='img/header4.jpg')}}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Origami Dragon</h5>
        <p>You can make a cool origami dragon like this!</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{{url_for('static', filename='img/header3.jpg')}}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Origami Chicken</h5>
        <p>Cock a doodle doo!</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock %}

origami/templates/order.html
{% extends 'base.html' %}

{% block main %}

<!-- display contents of user basket -->
<section>  
    <div class="container">
            <h3 class="text-center"><img src="{{url_for('static', filename='img/cart.png')}}" width="40">&nbsp;&nbsp;Your Shopping Cart</h3>
        <!-- each product on seperate row -->
        {% for product in order.products %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-12 card">
                    <h5 class="card-header">{{product.Category.name}} > {{product.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + product.image))}}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{product.description}}</p>  
                           <h5 class="text-right border-top">{{ "$%.2f"|format(product.price) }} (Qty: {{product.quantity}} piece)</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{product.id}}">
                            <input type="submit" value="Delete item" class="btn btn-primary mb-3 float-right" role="button">
                        </form>
                            </div>  
                        </div>                      
                    </div>
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
        
            <div class="mt-2 mb-4 text-right">
                <h5 class="mt-4">Total Price = {{ "$%.2f"|format(totalprice) }}</h5>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-outline-secondary empty" role="button">Empty Cart</a>&nbsp;&nbsp;&nbsp;
                <a href="{{ url_for('main.checkout') }}" class="btn btn-primary" role="button">
                <img src="{{url_for('static', filename='img/cart.png')}}" width="20">&nbsp;&nbsp;Go to Checkout
                </a>
            </div>
            
        </section>
    </div>
</section>
{% endblock %}

origami/templates/products.html
{% extends 'base.html' %}

{% block main %}
<div class="mycontents">
<!-- display products for the specific category -->
<section>

            <h2 class="text-center">Select a product from below</h2>

    <div class="card-columns">

        {% for product in products%}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+product.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{product.name}}</h4>
                <p class="card-text">{{product.description}}</p>
            </div>
            <div class="card-footer"><strong>Price: {{ "$%.2f"|format(product.price) }}</strong>
                <form action="{{ url_for('main.order') }}">
                    <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
                    <input class="btn btn-primary" type="submit" value="Add to Basket">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

</section>
{% endblock %}